use std::time::Instant;

use axum::{
    Router,
    extract::DefaultBodyLimit,
    middleware,
    response::Response,
    routing::{get, patch, post, put},
};

use crate::{
    AppState, CHAT_ATTACHMENT_BODY_LIMIT_BYTES, WORKSPACE_LOGO_BODY_LIMIT_BYTES,
    http::assets::static_asset,
    platform::native_browser::{native_browser_probe, select_directory, select_files},
};

pub(crate) fn app_router(state: AppState) -> Router {
    let auth_state = state.clone();

    Router::new()
        .route("/api/health", get(crate::http::auth::health))
        .route("/api/auth/status", get(crate::http::auth::auth_status))
        .route("/api/auth/login", post(crate::http::auth::auth_login))
        .route("/api/auth/logout", post(crate::http::auth::auth_logout))
        .route("/api/workspaces", get(crate::http::workspaces::workspaces))
        .route(
            "/api/workspaces/add",
            post(crate::http::workspaces::add_workspace),
        )
        .route(
            "/api/workspaces/manual",
            post(crate::http::workspaces::save_workspace_settings),
        )
        .route(
            "/api/workspaces/order",
            post(crate::http::workspaces::save_workspace_order),
        )
        .route(
            "/api/workspaces/{workspace_id}/files",
            get(crate::http::workspaces::workspace_files),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/children",
            get(crate::http::workspaces::workspace_file_children),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/content",
            post(crate::http::workspaces::workspace_file_content),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/blob",
            get(crate::http::workspaces::workspace_file_blob),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/save",
            post(crate::http::workspaces::save_workspace_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/delete",
            post(crate::http::workspaces::delete_workspace_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/files/rename",
            post(crate::http::workspaces::rename_workspace_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/logo",
            get(crate::http::workspaces::workspace_logo)
                .post(crate::http::workspaces::save_workspace_logo)
                .delete(crate::http::workspaces::clear_workspace_logo)
                .layer(DefaultBodyLimit::max(WORKSPACE_LOGO_BODY_LIMIT_BYTES)),
        )
        .route("/api/native/browser-probe.svg", get(native_browser_probe))
        .route("/api/native/select-directory", post(select_directory))
        .route("/api/native/select-files", post(select_files))
        .route(
            "/api/native/install-ripgrep",
            post(crate::http::workspaces::install_ripgrep),
        )
        .route("/api/settings", get(crate::http::settings::settings))
        .route(
            "/api/settings/general",
            post(crate::http::settings::save_general_settings),
        )
        .route(
            "/api/settings/web-search",
            post(crate::http::settings::save_web_search_settings),
        )
        .route(
            "/api/settings/memory",
            post(crate::http::settings::save_memory_settings),
        )
        .route(
            "/api/settings/spec",
            post(crate::http::settings::save_spec_settings),
        )
        .route(
            "/api/settings/plan",
            post(crate::http::settings::save_plan_settings),
        )
        .route(
            "/api/settings/prompts",
            post(crate::http::settings::save_prompt_settings),
        )
        .route(
            "/api/agent-definitions",
            get(crate::http::settings::agent_definitions),
        )
        .route(
            "/api/agent-definitions/create",
            post(crate::http::settings::create_agent_definition),
        )
        .route(
            "/api/agent-definitions/update",
            post(crate::http::settings::update_agent_definition),
        )
        .route(
            "/api/agent-definitions/delete",
            post(crate::http::settings::delete_agent_definition),
        )
        .route("/api/memory", get(crate::http::memory::memory_list))
        .route(
            "/api/memory/manual",
            post(crate::http::memory::create_manual_memory),
        )
        .route(
            "/api/memory/status",
            post(crate::http::memory::update_memory_status),
        )
        .route("/api/memory/edit", post(crate::http::memory::edit_memory))
        .route(
            "/api/memory/forget",
            post(crate::http::memory::forget_memory),
        )
        .route(
            "/api/memory/clear",
            post(crate::http::memory::clear_filtered_memories),
        )
        .route(
            "/api/memory/promote",
            post(crate::http::memory::promote_memory),
        )
        .route(
            "/api/memory/sources",
            get(crate::http::memory::memory_sources),
        )
        .route(
            "/api/memory/extraction/retry",
            post(crate::http::memory::retry_memory_extraction_job),
        )
        .route(
            "/api/memory/extraction/skip",
            post(crate::http::memory::skip_memory_extraction_job),
        )
        .route(
            "/api/memory/dream/run",
            post(crate::http::memory::run_memory_dream),
        )
        .route(
            "/api/memory/dream/jobs",
            get(crate::http::memory::memory_dream_jobs),
        )
        .route(
            "/api/memory/dream/jobs/{job_id}",
            get(crate::http::memory::memory_dream_job),
        )
        .route(
            "/api/memory/dream/jobs/{job_id}/changes",
            get(crate::http::memory::memory_dream_changes),
        )
        .route("/api/hooks", get(crate::http::hooks::hooks_settings))
        .route(
            "/api/hooks/global",
            post(crate::http::hooks::save_global_hooks),
        )
        .route(
            "/api/hooks/workspace",
            post(crate::http::hooks::save_workspace_hooks),
        )
        .route(
            "/api/hooks/import-claude",
            post(crate::http::hooks::import_claude_hooks),
        )
        .route("/api/hooks/test", post(crate::http::hooks::test_hooks))
        .route(
            "/api/scheduled-tasks",
            get(crate::http::scheduled_tasks::scheduled_tasks),
        )
        .route(
            "/api/scheduled-tasks/preview-next-run",
            post(crate::http::scheduled_tasks::preview_scheduled_task_next_run),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks",
            post(crate::http::scheduled_tasks::create_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}",
            get(crate::http::scheduled_tasks::scheduled_task)
                .patch(crate::http::scheduled_tasks::update_scheduled_task)
                .delete(crate::http::scheduled_tasks::delete_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/pause",
            post(crate::http::scheduled_tasks::pause_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/resume",
            post(crate::http::scheduled_tasks::resume_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/archive",
            post(crate::http::scheduled_tasks::archive_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/duplicate",
            post(crate::http::scheduled_tasks::duplicate_scheduled_task),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/run-now",
            post(crate::http::scheduled_tasks::run_scheduled_task_now),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-tasks/{task_id}/runs",
            get(crate::http::scheduled_tasks::scheduled_task_runs),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-task-runs/{scheduled_run_id}",
            get(crate::http::scheduled_tasks::scheduled_task_run),
        )
        .route(
            "/api/workspaces/{workspace_id}/scheduled-task-runs/{scheduled_run_id}/cancel",
            post(crate::http::scheduled_tasks::cancel_scheduled_task_run),
        )
        .route(
            "/api/workspaces/{workspace_id}/spec",
            get(crate::http::spec::workspace_spec).put(crate::http::spec::save_workspace_spec),
        )
        .route(
            "/api/workspaces/{workspace_id}/spec/settings",
            put(crate::http::spec::save_workspace_spec_settings),
        )
        .route(
            "/api/workspaces/{workspace_id}/spec/generate",
            post(crate::http::spec::generate_workspace_spec),
        )
        .route(
            "/api/workspaces/{workspace_id}/spec/jobs",
            get(crate::http::spec::workspace_spec_jobs),
        )
        .route(
            "/api/workspaces/{workspace_id}/plans",
            get(crate::http::plans::plans).post(crate::http::plans::create_plan),
        )
        .route(
            "/api/workspaces/{workspace_id}/plans/{plan_id}",
            patch(crate::http::plans::update_plan).delete(crate::http::plans::delete_plan),
        )
        .route(
            "/api/workspaces/{workspace_id}/plans/{plan_id}/action",
            post(crate::http::plans::plan_action),
        )
        .route(
            "/api/workspaces/{workspace_id}/plans/{plan_id}/steps/{step_id}/action",
            post(crate::http::plans::plan_step_action),
        )
        .route(
            "/api/workspaces/{workspace_id}/hooks/runs",
            get(crate::http::hooks::hook_runs),
        )
        .route(
            "/api/workspaces/{workspace_id}/hooks/runs/{hook_run_id}",
            get(crate::http::hooks::hook_run_detail),
        )
        .route(
            "/api/providers/manual",
            post(crate::http::settings::save_manual_provider),
        )
        .route(
            "/api/providers/delete",
            post(crate::http::settings::delete_provider),
        )
        .route(
            "/api/providers/test",
            post(crate::http::settings::test_provider),
        )
        .route(
            "/api/providers/models",
            post(crate::http::settings::provider_models),
        )
        .route(
            "/api/providers/models/refresh",
            post(crate::http::settings::refresh_provider_models),
        )
        .route(
            "/api/model-metadata",
            get(crate::http::settings::model_metadata),
        )
        .route(
            "/api/model-metadata/refresh",
            post(crate::http::settings::refresh_model_metadata),
        )
        .route(
            "/api/models/manual",
            post(crate::http::settings::save_manual_model),
        )
        .route(
            "/api/models/delete",
            post(crate::http::settings::delete_model),
        )
        .route(
            "/api/models/order",
            post(crate::http::settings::save_model_order),
        )
        .route(
            "/api/mcp/servers/manual",
            post(crate::http::settings::save_mcp_server),
        )
        .route(
            "/api/mcp/servers/delete",
            post(crate::http::settings::delete_mcp_server),
        )
        .route(
            "/api/skills/manual",
            post(crate::http::settings::save_skills),
        )
        .route(
            "/api/skills/refresh",
            post(crate::http::settings::refresh_skills),
        )
        .route("/api/ai-statistics", get(crate::http::chat::ai_statistics))
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/agent-team/enable",
            post(crate::http::agents::enable_agent_team),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/agent-team",
            get(crate::http::agents::agent_team_snapshot),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/agent-team/instances/create",
            post(crate::http::agents::create_agent_instances),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/agent-team/action",
            post(crate::http::agents::agent_runtime_action),
        )
        .route(
            "/api/workspaces/{workspace_id}/agent-tasks/{task_id}/action",
            post(crate::http::agents::agent_task_action),
        )
        .route(
            "/api/workspaces/{workspace_id}/chat/queue",
            post(crate::http::chat::queue_chat_message)
                .layer(DefaultBodyLimit::max(CHAT_ATTACHMENT_BODY_LIMIT_BYTES)),
        )
        .route(
            "/api/workspaces/{workspace_id}/chat/stream",
            post(crate::http::chat::stream_chat_response)
                .layer(DefaultBodyLimit::max(CHAT_ATTACHMENT_BODY_LIMIT_BYTES)),
        )
        .route(
            "/api/workspaces/{workspace_id}/chat/runs/{run_id}/stream",
            get(crate::http::chat::subscribe_chat_run),
        )
        .route(
            "/api/workspaces/{workspace_id}/chat/runs/{run_id}/cancel",
            post(crate::http::chat::cancel_chat_run),
        )
        .route(
            "/api/workspaces/{workspace_id}/chat/guidance",
            post(crate::http::chat::add_chat_guidance)
                .layer(DefaultBodyLimit::max(CHAT_ATTACHMENT_BODY_LIMIT_BYTES)),
        )
        .route(
            "/api/workspaces/{workspace_id}/context-usage",
            post(crate::http::chat::context_usage)
                .layer(DefaultBodyLimit::max(CHAT_ATTACHMENT_BODY_LIMIT_BYTES)),
        )
        .route(
            "/api/chat/questions/{question_id}/answer",
            post(crate::http::chat::answer_question),
        )
        .route(
            "/api/workspaces/{workspace_id}/ai-statistics/{request_id}",
            get(crate::http::chat::ai_statistics_detail),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/messages",
            get(crate::http::chat::chat_messages),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/todo-graph",
            get(crate::http::chat::chat_todo_graph),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/statistics",
            get(crate::http::chat::chat_statistics),
        )
        .route(
            "/api/workspaces/{workspace_id}/chats/{chat_id}/delete",
            post(crate::http::chat::delete_chat),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/status",
            get(crate::http::git::git_status),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/diff",
            get(crate::http::git::git_diff),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/stage",
            post(crate::http::git::stage_git_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/unstage",
            post(crate::http::git::unstage_git_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/discard",
            post(crate::http::git::discard_git_file),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/commit",
            post(crate::http::git::commit_staged_changes),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/commit-message",
            post(crate::http::git::generate_commit_message),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/branches",
            get(crate::http::git::git_branches),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/branches/switch",
            post(crate::http::git::switch_git_branch),
        )
        .route(
            "/api/workspaces/{workspace_id}/git/branches/create",
            post(crate::http::git::create_git_branch),
        )
        .route(
            "/api/workspaces/{workspace_id}/terminal/session",
            post(crate::http::terminal::create_terminal_session),
        )
        .route(
            "/api/workspaces/{workspace_id}/terminal/{session_id}/ws",
            get(crate::http::terminal::terminal_socket),
        )
        .fallback(static_asset)
        .layer(middleware::from_fn_with_state(
            auth_state,
            crate::http::auth::require_auth,
        ))
        .layer(middleware::from_fn(log_http_request))
        .with_state(state)
}

async fn log_http_request(request: axum::extract::Request, next: middleware::Next) -> Response {
    let started_at = Instant::now();
    let method = request.method().clone();
    let path = request.uri().path().to_string();
    tracing::info!(%method, %path, "HTTP request started");
    let response = next.run(request).await;
    tracing::info!(
        %method,
        %path,
        status = response.status().as_u16(),
        elapsed_ms = started_at.elapsed().as_millis() as u64,
        "HTTP request completed"
    );
    response
}
